/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GroupDialog: typeof import('./src/components/GroupDialog.vue')['default']
    HighQualityOutlined: typeof import('./src/components/Layout/menuSvg/HighQualityOutlined.vue')['default']
    Index: typeof import('./src/components/F2FPay/Index.vue')['default']
    Laboratory: typeof import('./src/components/Layout/menuSvg/Laboratory.vue')['default']
    LoginDialog: typeof import('./src/components/Layout/LoginDialog.vue')['default']
    Menus: typeof import('./src/components/Layout/Menus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleUpload: typeof import('./src/components/SingleUpload.vue')['default']
    SourceChange: typeof import('./src/components/plyrPlayer/components/SourceChange.vue')['default']
  }
}
