// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class VideoInfo {
    /**
     * Creates a new VideoInfo instance.
     * @param {Partial<VideoInfo>} [$$source = {}] - The source object to create the VideoInfo.
     */
    constructor($$source = {}) {
        if (!("formatName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["formatName"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("bitrate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bitrate"] = 0;
        }
        if (!("streams" in $$source)) {
            /**
             * @member
             * @type {VideoStream[]}
             */
            this["streams"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("streams" in $$parsedSource) {
            $$parsedSource["streams"] = $$createField3_0($$parsedSource["streams"]);
        }
        return new VideoInfo(/** @type {Partial<VideoInfo>} */($$parsedSource));
    }
}

export class VideoStream {
    /**
     * Creates a new VideoStream instance.
     * @param {Partial<VideoStream>} [$$source = {}] - The source object to create the VideoStream.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("codecName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codecName"] = "";
        }
        if (!("codecType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codecType"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("frameRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["frameRate"] = 0;
        }
        if (!("pixelFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pixelFormat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoStream instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoStream}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoStream(/** @type {Partial<VideoStream>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = VideoStream.createFrom;
const $$createType1 = $Create.Array($$createType0);
