// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string[]} names
 * @returns {$CancellablePromise<$models.ClassifyResultDTO[]>}
 */
export function ClassifyChannels(names) {
    return $Call.ByID(2371679242, names).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RuleConfigDTO>}
 */
export function GetDefaultRule() {
    return $Call.ByID(1466629167).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RuleConfigDTO>}
 */
export function GetRule() {
    return $Call.ByID(3631226634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AISettingsDTO>}
 */
export function GetSettings() {
    return $Call.ByID(3464685529).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * HasCustomRule 是否已保存用户自定义规则（非内置默认）
 * @returns {$CancellablePromise<boolean>}
 */
export function HasCustomRule() {
    return $Call.ByID(1663796773);
}

/**
 * @param {string} baseURL
 * @param {string} apiKey
 * @returns {$CancellablePromise<string[]>}
 */
export function ListModels(baseURL, apiKey) {
    return $Call.ByID(3492122954, baseURL, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ResetRule 清除自定义规则，恢复使用内置默认
 * @returns {$CancellablePromise<void>}
 */
export function ResetRule() {
    return $Call.ByID(2122470729);
}

/**
 * @param {$models.RuleConfigDTO} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveRule(cfg) {
    return $Call.ByID(4190545171, cfg);
}

/**
 * @param {$models.AISettingsDTO} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(92699720, settings);
}

// Private type creation functions
const $$createType0 = $models.ClassifyResultDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RuleConfigDTO.createFrom;
const $$createType3 = $models.AISettingsDTO.createFrom;
const $$createType4 = $Create.Array($Create.Any);
