// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ffmpeg$0 from "../internal/ffmpeg/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelProbes() {
    return $Call.ByID(1445934414);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1000407687);
}

/**
 * @param {string} url
 * @param {number} timeoutMs
 * @returns {$CancellablePromise<ffmpeg$0.VideoInfo>}
 */
export function GetVideoInfo(url, timeoutMs) {
    return $Call.ByID(1481565344, url, timeoutMs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function StartPlayback(url) {
    return $Call.ByID(4199656136, url);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopPlayback() {
    return $Call.ByID(2526641318);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StreamURL() {
    return $Call.ByID(4281435588);
}

// Private type creation functions
const $$createType0 = ffmpeg$0.VideoInfo.createFrom;
