// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function AppDataPath(name) {
    return $Call.ByID(536025368, name);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function Read(path) {
    return $Call.ByID(2454517752, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadPath(path) {
    return $Call.ByID(1894028175, path);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function SelectAndRead() {
    return $Call.ByID(1855648253).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SelectAndWrite opens a save-file dialog and writes data to the chosen path.
 * Returns the saved path, or "" when the user cancels.
 * @param {string} filename
 * @param {string} data
 * @returns {$CancellablePromise<string>}
 */
export function SelectAndWrite(filename, data) {
    return $Call.ByID(4076382516, filename, data);
}

/**
 * @param {string} path
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Write(path, data) {
    return $Call.ByID(3004069363, path, data);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
