// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AISettingsDTO {
    /**
     * Creates a new AISettingsDTO instance.
     * @param {Partial<AISettingsDTO>} [$$source = {}] - The source object to create the AISettingsDTO.
     */
    constructor($$source = {}) {
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("overwriteImportGroup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwriteImportGroup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISettingsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AISettingsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISettingsDTO(/** @type {Partial<AISettingsDTO>} */($$parsedSource));
    }
}

export class ClassifyResultDTO {
    /**
     * Creates a new ClassifyResultDTO instance.
     * @param {Partial<ClassifyResultDTO>} [$$source = {}] - The source object to create the ClassifyResultDTO.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassifyResultDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassifyResultDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClassifyResultDTO(/** @type {Partial<ClassifyResultDTO>} */($$parsedSource));
    }
}

export class PlaylistChannelInput {
    /**
     * Creates a new PlaylistChannelInput instance.
     * @param {Partial<PlaylistChannelInput>} [$$source = {}] - The source object to create the PlaylistChannelInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("fps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fps"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("codec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codec"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistChannelInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaylistChannelInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistChannelInput(/** @type {Partial<PlaylistChannelInput>} */($$parsedSource));
    }
}

export class PlaylistGroup {
    /**
     * Creates a new PlaylistGroup instance.
     * @param {Partial<PlaylistGroup>} [$$source = {}] - The source object to create the PlaylistGroup.
     */
    constructor($$source = {}) {
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {PlaylistItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaylistGroup}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new PlaylistGroup(/** @type {Partial<PlaylistGroup>} */($$parsedSource));
    }
}

export class PlaylistItem {
    /**
     * Creates a new PlaylistItem instance.
     * @param {Partial<PlaylistItem>} [$$source = {}] - The source object to create the PlaylistItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaylistItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistItem(/** @type {Partial<PlaylistItem>} */($$parsedSource));
    }
}

export class RematchResult {
    /**
     * Creates a new RematchResult instance.
     * @param {Partial<RematchResult>} [$$source = {}] - The source object to create the RematchResult.
     */
    constructor($$source = {}) {
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated"] = 0;
        }
        if (!("unknown" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unknown"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RematchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RematchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RematchResult(/** @type {Partial<RematchResult>} */($$parsedSource));
    }
}

export class RuleConfigDTO {
    /**
     * Creates a new RuleConfigDTO instance.
     * @param {Partial<RuleConfigDTO>} [$$source = {}] - The source object to create the RuleConfigDTO.
     */
    constructor($$source = {}) {
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {RuleGroupDTO[]}
             */
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleConfigDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuleConfigDTO}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        return new RuleConfigDTO(/** @type {Partial<RuleConfigDTO>} */($$parsedSource));
    }
}

export class RuleGroupDTO {
    /**
     * Creates a new RuleGroupDTO instance.
     * @param {Partial<RuleGroupDTO>} [$$source = {}] - The source object to create the RuleGroupDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("channels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["channels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleGroupDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuleGroupDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField1_0($$parsedSource["channels"]);
        }
        return new RuleGroupDTO(/** @type {Partial<RuleGroupDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PlaylistItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RuleGroupDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
