// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Clear() {
    return $Call.ByID(1738994993);
}

/**
 * @returns {$CancellablePromise<$models.PlaylistGroup[]>}
 */
export function ListGrouped() {
    return $Call.ByID(166366582).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RematchByRule 按当前 AI 规则表本地回填分组，不调用 LLM。
 * @returns {$CancellablePromise<$models.RematchResult>}
 */
export function RematchByRule() {
    return $Call.ByID(4020443849).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.PlaylistChannelInput} input
 * @returns {$CancellablePromise<void>}
 */
export function Upsert(input) {
    return $Call.ByID(2029761615, input);
}

// Private type creation functions
const $$createType0 = $models.PlaylistGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RematchResult.createFrom;
